create table players (
  id bigint generated by default as identity primary key,
  name text not null,
  player_number integer not null,
  position text not null,
  overall_rating integer not null,
  image_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint players_overall_rating_check
    check (overall_rating between 0 and 99),

  constraint players_position_check
    check (
      position in (
        'GK',
        'RB',
        'CB',
        'LB',
        'CDM',
        'CM',
        'CAM',
        'RW',
        'LW',
        'ST'
      )
    )
);